<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<AssemblyName>TwoRivers.Berelain</AssemblyName>
		<RootNamespace>TwoRivers.Berelain</RootNamespace>
		<PackageId>TwoRivers.Berelain</PackageId>
		<Title>TwoRivers.Berelain</Title>
		<ModuleAssetExcludes>$(ModuleAssetExcludes);wwwroot\lib\fontawesome\metadata\**;wwwroot\lib\fontawesome\js\**;wwwroot\lib\fontawesome\scss\**;wwwroot\lib\fontawesome\sprites\**;wwwroot\lib\fontawesome\sprites-full\**;wwwroot\lib\fontawesome\svgs\**;wwwroot\lib\fontawesome\svgs-full\**;wwwroot\lib\fontawesome*.zip</ModuleAssetExcludes>
		<ModuleDefaultAssetExcludes>$(ModuleDefaultAssetExcludes);wwwroot\lib\fontawesome\metadata\**;wwwroot\lib\fontawesome\js\**;wwwroot\lib\fontawesome\scss\**;wwwroot\lib\fontawesome\sprites\**;wwwroot\lib\fontawesome\sprites-full\**;wwwroot\lib\fontawesome\svgs\**;wwwroot\lib\fontawesome\svgs-full\**;wwwroot\lib\fontawesome*.zip</ModuleDefaultAssetExcludes>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OrchardCore.Module.Targets" Version="2.2.1" />
		<PackageReference Include="OrchardCore.ContentManagement" Version="2.2.1" />
		<PackageReference Include="OrchardCore.ContentManagement.Display" Version="2.2.1" />
		<PackageReference Include="OrchardCore.DisplayManagement" Version="2.2.1" />
		<PackageReference Include="OrchardCore.Settings.Core" Version="2.2.1" />
		<PackageReference Include="OrchardCore.ContentFields" Version="2.2.1" />
		<PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="2.2.1" />
		<PackageReference Include="OrchardCore.ResourceManagement" Version="2.2.1" />
		<PackageReference Include="YamlDotNet" Version="16.3.0" />
	</ItemGroup>

</Project>
